subject = {
    "inf": "informatika",
    "inffor": "informatika",
    "infmeg": "informatika",
    "infang": "informatika",
    "infangfor": "informatika",
    "infangmeg": "informatika",
    "infnem": "informatika",
    "infnemfor": "informatika",
    "infnemmeg": "informatika",
    "infspa": "informatika",
    "infspafor": "informatika",
    "infspameg": "informatika",
    "orosz": "orosz nyelv",
    "japan": "japán nyelv",
    "kinai": "kínai nyelv",
    "lovari": "lovári nyelv",
    "magyir": "magyar nyelv és irodalom",
    "magyid": "magyar mint idegen nyelv",
    "fldr": "földrajz",
    "fldrang": "földrajz",
    "fldrfra": "földrajz",
    "fldrnem": "földrajz",
    "fldrol": "földrajz",
    "mat": "matematika",
    "matang": "matematika",
    "latin": "latin nyelv",
    "spanyol": "spanyol nyelv",
    "fiz": "fizika",
    "enekzene": "ének-zene",
    "muvtort": "művészettörténet",
    "angol": "angol nyelv",
    "kem": "kémia",
    "kemang": "kémia",
    "katism": "katonai alapismeretek",
    "olasz": "olasz nyelv",
    "bio": "biológia",
    "horvatir": "horvát nemzetiségi nyelv és irodalom",
    "nnemetir": "német nemzetiségi nyelv és irodalom",
    "szlovakir": "szlovák nemzetiségi nyelv és irodalom",
    "vizu": "vizuális kultúra",
    "autorep": "autó- és repülőgép-szerelési ismeretek",
    "automat": "automatikai és elektronikai ismeretek",
    "egugy": "egészségügyi ismeretek",
    "elelm": "élelmiszeripari ismeretek",
    "epulgep": "épületgépészeti ismeretek",
    "erdvad": "erdészeti és vadgazdálkodási ismeretek",
    "faip": "faipari ismeretek",
    "foldm": "földmérési ismeretek",
    "gepgyartas": "gépgyártás-technológiai ismeretek",
    "hang": "hang-, film- és színháztechnikai ismeretek",
    "hangfor": "hang-, film- és színháztechnikai ismeretek",
    "hangmeg": "hang-, film- és színháztechnikai ismeretek",
    "infoism": "informatikai ismeretek",
    "infoismfor": "informatikai ismeretek",
    "infoismmeg": "informatikai ismeretek",
    "irodaiugyv": "irodai ügyviteli ismeretek",
    "irodugyfor": "irodai ügyviteli ismeretek",
    "irodugymeg": "irodai ügyviteli ismeretek",
    "jazz": "jazz-zenész ismeretek",
    "kepz": "képző- és iparművészeti ismeretek",
    "ker": "kereskedelmi ismeretek",
    "kiadvszerk": "kiadványszerkesztési ismeretek",
    "klassz": "klasszikuszenész-ismeretek",
    "kozmetikai": "kozmetikai ismeretek",
    "kornyved": "környezetvédelmi ismeretek",
    "kozg": "közgazdasági ismeretek",
    "kozlautmat": "közlekedésautomatikai ismeretek",
    "kozutilegi": "közúti és légi közlekedési, szállítmányozási és logisztikai ismeretek",
    "magmelyep": "magas- és mélyépítési ismeretek",
    "mechatron": "mechatronikai ismeretek",
    "mezerdgep": "mezőgazdasági és erdészeti gépésztechnikai ismeretek",
    "mezog": "mezőgazdasági ismeretek",
    "ped": "pedagógiai ismeretek",
    "rendkozsz": "rendészeti és közszolgálati ismeretek",
    "sport": "sport ismeretek",
    "tanc": "táncos ismeretek",
    "turiszt": "turisztikai ismeretek",
    "utvasuthid": "út-, vasút- és hídépítési ismeretek",
    "vasutgep": "vasútgépészeti ismeretek",
    "vegy": "vegyész ismeretek",
    "vegynem": "vegyész ismeretek",
    "vegyip": "vegyipari ismeretek",
    "vend": "vendéglátóipari ismeretek",
    "filo": "filozófia",
    "etarsetipr": "ember- és társadalomismeret, etika - projekt készítése",
    "embetipr": "emberismeret és etika – projekt készítése",
    "horvnepismpr": "horvát nemzetiségi népismeret – projekt készítése",
    "momedpr": "mozgóképkultúra és médiaismeret – projekt készítése",
    "rnepismpr": "román nemzetiségi népismeret – projekt készítése",
    "rcnepismpr": "roma/cigány nemzetiségi népismeret – projekt készítése",
    "tarspr": "társadalomismeret – projekt készítése",
    "vizupr": "vizuális kultúra – projekt készítése",
    "nemet": "német nyelv",
    "belrendism": "belügyi rendészeti ismeretek",
    "drama": "dráma",
    "momed": "mozgóképkultúra és médiaismeret",
    "tort": "történelem",
    "tortang": "történelem",
    "tortnem": "történelem",
    "francia": "francia nyelv",
    "bioang": "biológia",
    "tars": "társadalomismeret",
    "lengyel": "lengyel nyelv",
    "portugal": "portugál nyelv",
    "roman": "román nyelv",
    "szlovak": "szlovák nyelv",
    "honvedelmi": "honvédelmi ismeretek",
    "szoc": "szociális ismeretek",
    "tavkozl": "távközlési ismeretek",
    "tavkozlfor": "távközlési ismeretek",
    "tavkozlmeg": "távközlési ismeretek",
    "vizugyi": "vízügyi ismeretek",
    "gazdism2": "kémia",
    "tortma": "történelem idegen nyelven",
    "tortfra": "történelem idegen nyelven",
    "torthor": "történelem idegen nyelven",
    "tortol": "történelem idegen nyelven",
    "tortor": "történelem idegen nyelven",
    "tortrom": "történelem idegen nyelven",
    "tortspa": "történelem idegen nyelven",
    "tortsze": "történelem idegen nyelven",
    "tortszlo": "történelem idegen nyelven",
    "fizma": "fizika idegen nyelven",
    "fizang": "fizika idegen nyelven",
    "fiznem": "fizika idegen nyelven",
    "gazdispr": "gazdasági ismeretek - projekt készítése",
    "nnemnepismpr": "német nemzetiségi népismeret - projekt készítése",
    "szenepismpr": "szerb nemzetiségi népismeret - projekt készítése",
    "szlonepismpr": "szlovák nemzetiségi népismeret - projekt készítése",
    "uturizpr": "utazás és turizmus - projekt készítése",
    "matma": "matematika idegen nyelven",
    "matfra": "matematika idegen nyelven",
    "mathor": "matematika idegen nyelven",
    "matnem": "matematika idegen nyelven",
    "matol": "matematika idegen nyelven",
    "mator": "matematika idegen nyelven",
    "matrom": "matematika idegen nyelven",
    "matspa": "matematika idegen nyelven",
    "matsze": "matematika idegen nyelven",
    "matszlo": "matematika idegen nyelven",
    "beas": "beás nyelv",
    "bolgar": "bolgár nyelv",
    "eszperanto": "eszperantó nyelv",
    "holland": "holland nyelv",
    "horvat": "horvát nyelv",
    "szerb": "szerb nyelv",
    "szloven": "szlovén nyelv",
    "ujgorog": "újgörög nyelv",
    "pszichologia": "pszichológia",
    "termtud": "természettudomány",
    "kemma": "kémia idegen nyelven",
    "kemnem": "kémia idegen nyelven",
    "fldrma": "földrajz idegen nyelven",
    "fldrspa": "földrajz idegen nyelven",
    "romanir": "román nemzetiségi nyelv és irodalom",
    "szerbir": "szerb nemzetiségi nyelv és irodalom",
    "artist": "artista ismeretek",
    "egugytech": "egészségügyi technikai ismeretek",
    "egyh": "egyházzenész-ismeretek",
    "elelmgep": "élelmiszeripari gépésztechnikai ismeretek",
    "fodraszati": "fodrászati ismeretek",
    "gazipari": "gázipari és fluidumkitermelési ismeretek",
    "gyakszin": "gyakorlatosszínész-ismeretek",
    "hajozasi": "hajózási technikai ismeretek",
    "idnyeugyv": "idegennyelvű ügyviteli ismeretek",
    "kerang": "kereskedelmi ismeretek",
    "kert": "kertészeti és parképítési ismeretek",
    "kozgang": "közgazdasági ismeretek",
    "kozgfra": "közgazdasági ismeretek",
    "kozgnem": "közgazdasági ismeretek",
    "kozmuv": "közművelődési ismeretek",
    "nepz": "népzenész-ismeretek",
    "nyomd": "nyomdaipari technikai ismeretek",
    "opt": "optikai ismeretek",
    "postaforg": "postaforgalmi ismeretek",
    "szorak": "szórakoztatózenész-ismeretek",
    "turisztang": "turisztikai ismeretek",
    "turisztnem": "turisztikai ismeretek",
    "vasutuzemi": "vasútüzemi közlekedési, szállítmányozási és logisztikai ismeretek",
    "vegyang": "vegyész ismeretek",
    "heber": "héber nyelv",
    "": "héber nyelv",
    "bioma": "biológia idegen nyelven",
    "infma": "informatika idegen nyelven",
    "infmafor": "informatika idegen nyelven",
    "infmameg": "informatika idegen nyelven",
    "inffra": "informatika idegen nyelven",
    "inffrafor": "informatika idegen nyelven",
    "infframeg": "informatika idegen nyelven",
    "infhor": "informatika idegen nyelven",
    "infhorfor": "informatika idegen nyelven",
    "infhormeg": "informatika idegen nyelven",
    "infrom": "informatika idegen nyelven",
    "infromfor": "informatika idegen nyelven",
    "infrommeg": "informatika idegen nyelven",
    "infsze": "informatika idegen nyelven",
    "infszefor": "informatika idegen nyelven",
    "infszemeg": "informatika idegen nyelven",
    "enekzenenem": "ének-zene",
    "finn": "finn nyelv",
    "ukran": "ukrán nyelv",
    "fizspa": "fizika idegen nyelven",
    "konyip": "könnyűipari ismeretek",
    "biosze": "biológia idegen nyelven",
    "irodaiugyvfor": "irodai ügyviteli ismeretek",
    "irodaiugyvmeg": "irodai ügyviteli ismeretek",
    "vegyesz": "vegyész ismeretek",
    "infoismFOR": "informatikai ismeretek",
    "banyamuv": "bányaművelési ismeretek",
    "irodugy": "irodai ügyviteli ismeretek",
    "kemsze": "kémia idegen nyelven",
    "fldrhor": "földrajz idegen nyelven",
    "fldrrom": "földrajz idegen nyelven",
    "fldrszlo": "földrajz idegen nyelven",
    "bionem": "biológia idegen nyelven",
    "fizsze": "fizika idegen nyelven",
    "epit": "építőipar ismeretek",
    "gep": "gépészet ismeretek",
    "kornyviz": "környezetvédelem-vízgazdálkodás ismeretek",
    "kozl": "közlekedés ismeretek",
    "kozlgep": "közlekedésgépész ismeretek",
    "mezogep": "mezőgazdasági gépész ismeretek",
    "rend": "rendészet ismeretek",
    "szep": "szépészet ismeretek",
    "ugyvit": "ügyvitel ismeretek",
    "ugyvitfor": "ügyvitel ismeretek",
    "ugyvitmeg": "ügyvitel ismeretek",
    "vill": "villamosipar és elektronika ismeretek",
    "banyasz": "bányászat ismeretek",
    "epitnem": "építőipar ismeretek",
    "kozlepit": "közlekedésépítő ismeretek",
    "vendang": "vendéglátóipar ismeretek",
    "biofra": "biológia idegen nyelven",
    "fizhor": "fizika idegen nyelven",
    "vizusze": "vizuális kultúra",
    "kemszlo": "kémia idegen nyelven",
    "bioszlo": "biológia idegen nyelven",
    "biorom": "biológia idegen nyelven",
    "turisztangma": "turisztika ismeretek",
    "turisztnemma": "turisztika ismeretek",
    "turisztszlo": "turisztika ismeretek",
    "turisztszloma": "turisztika ismeretek",
    "fizfra": "fizika idegen nyelven",
    "vizuhor": "vizuális kultúra",
    "momedprang": "mozgóképkultúra és médiaismeret - projekt készítése",
    "momedang": "mozgóképkultúra és médiaismeret",
    "vendnem": "vendéglátóipar ismeretek",
    "rajzvizupr": "rajz és vizuális kultúra - projekt készítése",
    "rajzvizu": "rajz és vizuális kultúra",
    "elekt": "elektronikai alapismeretek",
    "kermark": "kereskedelmi és marketing alapismeretek",
    "kozgelm": "közgazdasági alapismeretek (elméleti gazdaságtan)",
    "kozguzl": "közgazdasági alapismeretek (üzleti gazdaságtan)",
    "kozluzemv": "közlekedési alapismeretek (közlekedés-üzemvitel)",
    "okt": "oktatási alapismeretek",
    "vendid": "vendéglátás-idegenforgalom alapismeretek",
    "rajzvizusze": "rajz és vizuális kultúra",
    "cnepismpr": "cigány kisebbségi népismeret - projekt készítése",
    "gazdisprnem": "gazdasági ismeretek - projekt készítése",
    "tarsprang": "társadalomismeret - projekt készítése",
    "tarsprnem": "társadalomismeret - projekt készítése",
    "tarsprszlo": "társadalomismeret - projekt készítése",
    "kermarkang": "kereskedelmi és marketing alapismeretek",
    "kozgelmang": "közgazdasági alapismeretek (elméleti gazdaságtan)",
    "kozgelmfra": "közgazdasági alapismeretek (elméleti gazdaságtan)",
    "kozgelmnem": "közgazdasági alapismeretek (elméleti gazdaságtan)",
    "kozltech": "közlekedési alapismeretek (közlekedéstechnika)",
    "muvkom": "művelődési és kommunikációs alapismeretek",
    "vendidang": "vendéglátás-idegenforgalom alapismeretek",
    "vendidnem": "vendéglátás-idegenforgalom alapismeretek",
    "vendidszlo": "vendéglátás-idegenforgalom alapismeretek",
    "muvtortol": "művészettörténet",
    "infert": "informatika",
    "infangert": "informatika",
    "tarsprhor": "társadalomismeret - projekt készítése",
    "elektang": "elektronikai alapismeretek",
    "infoismang": "informatikai alapismeretek",
    "infoismangfor": "informatikai alapismeretek",
    "infoismangmeg": "informatikai alapismeretek",
    "infmaert": "informatika idegen nyelven",
    "inffraert": "informatika idegen nyelven",
    "infhorert": "informatika idegen nyelven",
    "infnemert": "informatika idegen nyelven",
    "infromert": "informatika idegen nyelven",
    "infszeert": "informatika idegen nyelven",
    "infspaert": "informatika idegen nyelven",
    "gazdis1pr": "gazdasági ismeretek - projekt készítése",
    "nnemet": "német nemzetiségi nyelv és irodalom",
    "dramafra": "dráma",
    "abrgeom": "ábrázoló és művészeti geometria",
    "fldror": "földrajz idegen nyelven",
    "szlenepismpr": "szlovén népismeret - projekt készítése",
    "biohor": "biológia idegen nyelven",
    "egugyang": "egészségügyi alapismeretek",
    "nszloven": "szlovén nemzetiségi nyelv",
    "gazdism2ang": "gazdasági ismeretek (II. változat)"
}
