name: Scraper CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone external repository from SourceHut
      run: git clone https://git.sr.ht/~boa/duvet

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run Go program
      run: cd duvet && go run -v ./cli/duvet/main.go example_configs/erettsegi.yaml && mv erettsegi/day.csv ../ && cd ..

    - name: Run Python script
      run: python process.py

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add data
      run: git add day.csv && git commit -m "add new data"

    - name: Push data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
